### PR TITLE
Frontend functionality of Currency API

### PR DESCRIPTION
**Pull request by sadiuysal**
Frontend functionality of Currency API is implemented and ready to merge.

### CODE REVIEW

**Comment by ibrahimorhan** [comment]
I have reviewed your code. In html part there is an element in which you wrote the date. But after clicking submit button it doesn't change. I guess you should also update that element or delete it

**Comment by ibrahimorhan** [comment]
Other than that it seems fine to me

**Comment by ocebenzer** [comment]
I accidentally overrode the index.html file, fixing the problem as soon as possible. Sorry but can you wait ~5 mins to merge?

**Comment by sadiuysal** [comment]
> I have reviewed your code. In html part there is an element in which you wrote the date. But after clicking submit button it doesn't change. I guess you should also update that element or delete it

Oh I overlooked that one. I will fix it. Thank you

**Comment by ocebenzer** [comment]
> I accidentally overrode the index.html file, fixing the problem as soon as possible. Sorry but can you wait ~5 mins to merge?

It should be ok now.

**Comment by hasandemirkiran** [comment]
Seems okay.

**Comment by ocebenzer** [comment]
There seem to be files that we do not need anymore, these files can be deleted to avoid conflict
ex: *.png and *.jpg files, .DS_STORE files

**Pull request merged**
