### PR TITLE
iOS Alcan - MyCartViewController and related changes

### PR DESCRIPTION
**Pull request by alcanunsal**
- MyCartViewController
- API calls related to cart
- CartCell
- added appicon

### CODE REVIEW

**Comment by sadiuysal** [comment]
Looks good to me. Thanks for your efforts!

**Review by bestegoger — APPROVED** [review]
Looks perfect! Ready to merge 👍

**Review by sadiuysal — APPROVED** [review]
Nice work!

**Comment by alcanunsal** [comment]
We have 2/3 approves, therefore I am doing the merge.

**Pull request merged**
