### PR TITLE
Bazaar API Center v1.0.1

### PR DESCRIPTION
**Pull request by ocebenzer**

### CODE REVIEW

**Comment by ocebenzer** [comment]
All conflicts are cache files, this should not be a problem

**Comment by alcanunsal** [comment]
Nice work everyone! #gozleryasli :)

**Comment by mehmetkemaloglu** [comment]
We did beautiful work. Good job team!

**Comment by hasandemirkiran** [comment]
Good Job Team!

**Comment by ibrahimorhan** [comment]
Health to your hands. Our application is slighlty worse than instagram, much better than facebook

**Comment by sadiuysal** [comment]
> Health to your hands. Our application is slighlty worse than instagram, much better than facebook

You took the word from my mouth, thanks everyone for your effort.

**Comment by firatbulut19** [comment]
Great work team! Ready to make some money.

**Pull request merged**
