### PR TITLE
Front end development nasa news

### PR DESCRIPTION
**Pull request by ibrahimorhan**
Front end for news is completed. However it would be good if you check error handling

### CODE REVIEW

**Comment by hasandemirkiran** [comment]
Thank you for not merging to the master branch and also resolve conflicts.

**Comment by firatbulut19** [comment]
I reviewed the code, seems OK for the most part. No conflicts, which is good. I will try to improve error handling for the dates that are not allowed by the API.

**Comment by ocebenzer** [comment]
It looks like it can be merged without any errors, congratulations!

**Comment by alcanunsal** [comment]
I don't see any problem apart from your attempt at merging with the master branch, which you realized very fast. I figure this concludes our frontend development. Is there any other frontend implementations that are missing that you are aware of?

**Comment by mehmetkemaloglu** [comment]
Seems nicely working.

**Comment by sadiuysal** [comment]
Everything seems fine for the frontend. However I realized that when our page loaded initially, some numbers in the covid19 were undefined. Is this a problem?  
Screen Shot 2020-05-27 at 21 23 22

**Pull request merged**
