### PR TITLE
iOS - Lists (final version)

### PR DESCRIPTION
**Pull request by bestegoger**
I think once approved this merge will finalize the Product Lists implementation (hopefully 🙏 ). 

- "Add to list" functionality is done.
- An alert is displayed when the user wants to delete a list with products in it.
- Also, a small change to the product detail page for choosing the amount of a product to add to cart. Now the default amount is 1.

Please review!

### CODE REVIEW

**Comment by muhsinetki** [comment]
I found a bug affecting the part you work for. I set custom error instead of forcing optional error. (it fixed).

Can we share lists? I couldn't find the feature to share lists, if we don't add such a feature, the rest of it works fine.

**Comment by bestegoger** [comment]
> I found a bug affecting the part you work for. I set custom error instead of forcing optional error. (it fixed).
> 
> Can we share lists? I couldn't find the feature to share lists, if we don't add such a feature, the rest of it works fine.

Thanks for your comment and contribution.

Actually in this project we don't have such requirement as sharing the lists. But for some reason the API requests concerned with the product lists made me think that we need to have such specifications [You can see it [here](https://github.com/bounswe/bounswe2020group9/wiki/API-Documentation#apiuseruser_idlists-get-post)]. That is why I had implemented the lists in this way for example adding a list requires specifying whether it is private or public. But I am actually not sure. 

I can change anything in the code, if we can agree on sth either this or that way. 😊

**Review by muhsinetki — APPROVED** [review]

**Review by alcanunsal — APPROVED** [review]
I think it looks good, thanks for your effort.

**Comment by alcanunsal** [comment]
I think we can drop the list-sharing functionality, at least for this milestone. It doesn't seem like a crucial functionality in my opinion but since this affects frontend and backend also, maybe we should discuss it as the whole team first.

**Review by sadiuysal — APPROVED** [review]
Everything looks fine. Thanks for your efforts

**Pull request merged**
