### PR TITLE
ios alcan - v1 of product detail view and searching in main screen

### PR DESCRIPTION
**Pull request by alcanunsal**
- created an extension to UIImage class that could be used for easier image download with cache
- added resources for star rating component, anyone can use them easily without having to do additional steps
- added a view controller for search results, which could also be used for category filtering results @sadiuysal 

- added product detail view with backend connection for the image
- implemented the backend connection for product images
- added swipe to delete gesture to search history
- added searching functionality to main screen with following properties: searching in categories and brands, search history.
- fixed the scrolling bug in the main screen

p.s. I had to leave search bar compatibility for older iOS version to my next submit since it was taking too long to download an iOS version.

### CODE REVIEW

**Review by sadiuysal — APPROVED** [review]
Looks good to me. Thanks for your efforts

**Comment by muhsinetki** [comment]
```
        if #available(iOS 13.0, *) {
            searchTextField = searchBar.searchTextField
        } else {
            self.searchBar.barStyle = .default
            if let searchField = searchBar.value(forKey: "searchField") as? UITextField {
                searchTextField = searchField
             }
         }
```

You don't need to download older iOS version .

 When I review the code, you switch the searchbar back to uitextfield. Instead of doing this, creating the searchbar as textfield at the beginning would be good for both readability and solving the compatibility problem, and we wouldn't write extra code

**Comment by alcanunsal** [comment]
@muhsinetki I downloaded an earlier version of iOS in order to see what's wrong and fix it since I cannot see whats wrong while I was using iOS13+. As it comes to the bug, I have already fixed it but thanks anyways for your input.

**Review by bestegoger — APPROVED** [review]
I think we can merge and close this pr.

**Pull request merged**
