### PR TITLE
News api

### PR DESCRIPTION
**Pull request by firatbulut19**
2 functions. 
First one gets the NASA picture of the day using NASA API. Then, it parses the explanation of that picture and finds entities using Dandelion API. Finally, it searches for articles containing the entities and returns them according to their relevance to the original NASA picture explanation.
http://127.0.0.1:5000/api/news/nasa
Second one returns the most popular news articles of the day.
http://127.0.0.1:5000/api/news

### CODE REVIEW

**Comment by hasandemirkiran** [comment]
Seems good to push. Well done.

**Comment by hasandemirkiran** [comment]
Seems some conflicts please resolve them.

**Comment by ocebenzer** [comment]
There are conflicts, be careful to not delete old files

**Comment by alcanunsal** [comment]
For me it seems fine, doesn't have any problems if you resolve some conflicts. Thanks for your effort.

**Comment by ibrahimorhan** [comment]
ı have solved the conflicts and it is ready to be merged :)

**Comment by hasandemirkiran** [comment]
Congrats, ibrahimorhan! Now it is perfect to pull. It is your allowance.

**Comment by alcanunsal** [comment]
1 down, other branches to go! Well done 🥇

**Pull request merged**
